version: "3.8"

services:
  backend:
    build:
      context: ./backend/portfolio
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: urluser
      SPRING_DATASOURCE_PASSWORD: urlpassword

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend/portfolio
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
